highlighter: rouge
markdown: kramdown
permalink: /:title.html
paginate: 5
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
port: 3000
safe: true

name: Nenad Bubalo - Mouse On The Keys Blog
description: Data Engineer based in Berlin. Writing about data platforms, AWS, dbt, Airflow, and Python.
url: https://nenadbubalo.com
title: Nenad Bubalo
author: Nenad Bubalo
avatar: slika.png
email: nenad.bubalo@mail.com
facebook: nenad.bubalo
github: mouseonthekeys
instagram: grumpyraccoon
lastfm: MouseOnTheKeyz
linkedin: nenad-bubalo
xing: Nenad_Bubalo
stackoverflow: users/11832202/mouse-on-the-keys
disqus: mouseonthekeys

exclude: [vendor]
